env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

language: cpp

services:
  - docker

notifications:
  email: false

before_install:
- export D2K=mathlab/deal2lkit:dev-debugrelease
- docker pull $D2K
- docker run -P -v `pwd`:/home/dealii/pi-DoMUS:rw $D2K /bin/sh -c "cd pi-DoMUS; ./scripts/check_indentation.sh"

script:
- docker run -P -v `pwd`:/home/dealii/pi-DoMUS:rw $D2K /bin/sh -c "mkdir pi-DoMUS/build; cd pi-DoMUS/build; cmake -GNinja -DENABLE_DOCUMENTATION=OFF  -DENABLE_ALL_EXECUTABLES=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE ../; ninja -j2"
- docker run -P -v `pwd`:/home/dealii/pi-DoMUS:rw $D2K /bin/sh -c "cd pi-DoMUS/build; ctest -j2 -V"
